export { default as Span } from "./Span.astro"
export { default as Strong } from "./Strong.astro"
export { default as Em } from "./Em.astro"
export { default as Link } from "./Link.astro"
export { default as Email } from "./Email.astro"